import { PatientSession } from "../types/patient";

export const INITIAL_PATIENTS = (nowMs: number): PatientSession[] => [
  {
    patientId: "somchai-uuid-12345",
    status: "active",
    startedAt: new Date(nowMs - 2 * 60000).toISOString(), // 2 min ago
    updatedAt: new Date(nowMs - 2 * 60000).toISOString(),
    formData: {
      firstName: "Somchai",
      lastName: "Jaidee",
      middleName: "",
      dateOfBirth: "1985-03-15",
      gender: "Male",
      phone: "+66 89 123 4567",
      email: "",
      address: ["123 Sukhumvit Rd, Bangkok 10110"],
      language: "Thai",
      nationality: "Thai",
      religion: "Buddhism",
      emergencyContact: "",
      emergencyRelationship: "",
      emergencyPhone: "",
    },
    lastActiveField: "email",
  },
  {
    patientId: "nipa-uuid-12345",
    status: "submitted",
    startedAt: new Date(nowMs - 15 * 60000).toISOString(),
    updatedAt: new Date(nowMs - 8 * 60000).toISOString(), // 8 min ago
    formData: {
      firstName: "Nipa",
      lastName: "Wongsri",
      middleName: "",
      dateOfBirth: "1990-05-12",
      gender: "Female",
      phone: "+66 81 234 5678",
      email: "nipa.wongsri@email.com",
      address: ["456 Phahonyothin Rd, Bangkok 10400"],
      language: "Thai",
      nationality: "Thai",
      religion: "Buddhism",
      emergencyContact: "Somsak Wongsri",
      emergencyRelationship: "Father",
      emergencyPhone: "+66 81 987 6543",
    },
  },
  {
    patientId: "prasit-uuid-12345",
    status: "inactive",
    startedAt: new Date(nowMs - 25 * 60000).toISOString(),
    updatedAt: new Date(nowMs - 15 * 60000).toISOString(), // 15 min ago
    formData: {
      firstName: "Prasit",
      lastName: "Tanaka",
      middleName: "Takeshi",
      dateOfBirth: "1988-11-05",
      gender: "Male",
      phone: "+66 92 345 6789",
      email: "prasit.tanaka@email.com",
      address: ["789 Sukhumvit Rd, Bangkok 10110"],
      language: "Japanese",
      nationality: "Japanese",
      religion: "Shinto",
      emergencyContact: "Keiko Tanaka",
      emergencyRelationship: "Mother",
      emergencyPhone: "+66 92 987 6543",
    },
  },
  {
    patientId: "malee-uuid-12345",
    status: "submitted",
    startedAt: new Date(nowMs - 40 * 60000).toISOString(),
    updatedAt: new Date(nowMs - 22 * 60000).toISOString(), // 22 min ago
    formData: {
      firstName: "Malee",
      lastName: "Saengdao",
      middleName: "",
      dateOfBirth: "1975-01-20",
      gender: "Female",
      phone: "+66 83 456 7890",
      email: "malee.saengdao@email.com",
      address: ["101 Ramkhamhaeng Rd, Bangkok 10240"],
      language: "Thai",
      nationality: "Thai",
      religion: "Buddhism",
      emergencyContact: "Somchai Saengdao",
      emergencyRelationship: "Husband",
      emergencyPhone: "+66 83 987 6543",
    },
  },
  {
    patientId: "krit-uuid-12345",
    status: "submitted",
    startedAt: new Date(nowMs - 60 * 60000).toISOString(),
    updatedAt: new Date(nowMs - 35 * 60000).toISOString(), // 35 min ago
    formData: {
      firstName: "Krit",
      lastName: "Boonsong",
      middleName: "",
      dateOfBirth: "1995-09-12",
      gender: "Male",
      phone: "+66 84 567 8901",
      email: "krit.boonsong@email.com",
      address: ["202 Lat Phrao Rd, Bangkok 10310"],
      language: "Thai",
      nationality: "Thai",
      religion: "Christian",
      emergencyContact: "Sunee Boonsong",
      emergencyRelationship: "Mother",
      emergencyPhone: "+66 84 987 6543",
    },
  },
];
